### ISSUE TITLE
MQ Retry queues

### ISSUE THREAD

**Issue by silverdaz** [EGA-archive/LocalEGA#103]
### Description
When a message is rejected because another service is not available,
we could send the message to a dead-letter exchange/queue and let it retry a few seconds later.

### Proposed solution
There are several solution described [here](https://engineering.nanit.com/rabbitmq-retries-the-full-story-ca4cc6c5b493). This is not a new concept.

We can implement an exchange with a timeout, which requires a plugin insertion, or we can duplicate all the relevant queues with a dead-letter equivalent and set up the exchange routing keys accordingly. The latter is a bit more verbose, but nonetheless somehow standard.

**Comment by eandersson** [comment]
You have an example implementation that can be almost mapped 1on1 to amqpstorm here as well.
https://stackoverflow.com/questions/17014584/how-to-create-a-delayed-queue-in-rabbitmq

**Comment by silverdaz** [comment]
Closing it as the architecture around the message queues as changed
