### ISSUE TITLE
TLS handshake problem

### ISSUE THREAD

**Issue by mrspock434** [EGA-archive/LocalEGA#128]
2021-11-21 12:07:44.962 [error] <0.1477.0> Shovel 'to_cega' failed to connect (URI: amqps://cega-mq:5671/lega): {tls_alert,{handshake_failure,"TLS client: In state wait_cert at ssl_handshake.erl:1901 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}"}}
 
I can't seem to shake offf this problem...... since lega->cega mq is down, users are not recognized from fake cega on inbox login attempt.... As far as I remember, an older commit did not have this issue.

**Comment by silverdaz** [comment]
What does `make ps` (or `docker-compose ps`) say?
Did you bootstrap and therefore generate the (self-signed) necessary certificates?

**Comment by mrspock434** [comment]
make ps does not show any services as exited. 

Question: The test suite keeps failing. The upload part is working fine, but ingestion does not seem to work. Is the ingestion process supposed to be automatic, or is it triggered by seperately provided service (prepared by user), which sends the MQ messages?

**Comment by silverdaz** [comment]
Trigger by a separate service (we call it the submitter portal).
You can send the MQ message yourself, as a fake trigger.

**Comment by mrspock434** [comment]
Hey, thanks for the reply. So if I understand correctly, it's up to the user to prepare their own submitter portal (own implementation)? This portal then sends RabbitMQ messages to ingestion? I believe this is information of crucial importance and should be included as a disclaimer in the README, since users (like myself) who have little or no familiarity with the EGA infrastructure can get confused quickly.

**Comment by silverdaz** [comment]
Central EGA currently hosts the submitter portal, and sends a trigger via the message broker.
In case you are only connected to the fake Central EGA instance, you can send a fake trigger as part of your tests.
However, this comment is not related to the initial issue. Are you sure the bootstrapping went through without errors?

**Comment by silverdaz** [comment]
No answer from the original reporter, closing the issue
