### ISSUE TITLE
DB & MQ retry logic

### ISSUE THREAD

**Issue by juhtornr** [EGA-archive/LocalEGA#13]
<a href="https://github.com/silverdaz"><img src="https://avatars3.githubusercontent.com/u/465385?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silverdaz](https://github.com/silverdaz)**
_Monday Dec 10, 2018 at 18:35 GMT_
_Originally opened as https://github.com/NBISweden/LocalEGA/issues/381_

----

Improve the robustness of the DB and MQ connections

**Comment by juhtornr** [comment]
<a href="https://github.com/juhtornr"><img src="https://avatars1.githubusercontent.com/u/396559?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [juhtornr](https://github.com/juhtornr)**
_Thursday Dec 20, 2018 at 08:17 GMT_

----

@silverdaz Makes sense but can you be little bit more specific? What is the problem at the moment?

**Comment by silverdaz** [comment]
For example, when the message broker is restarted, all the connected components lose their connection and crash.
The retry logic is ready, but not merged.

**Comment by juhtornr** [comment]
Time estimate: 2 days
