### ISSUE TITLE
Unable to complete localfega installation

### ISSUE THREAD

**Issue by claudiologiudice** [EGA-archive/LocalEGA#133]
Dockerfile:47
--------------------
  46 |     
  47 | >>> RUN ldconfig -v                                  && \
  48 | >>>     groupadd -g ${LEGA_GID} -r ${LEGA_GROUPNAME} && \
  49 | >>>     useradd -M -g ${LEGA_GROUPNAME} -u ${LEGA_UID} ${LEGA_USERNAME} && \
  50 | >>>     mkdir -p /ega/staging                        && \
  51 | >>>     chgrp ${LEGA_USERNAME} /ega/staging          && \
  52 | >>>     chmod 2770 /ega/staging                      && \
  53 | >>>     mkdir -p /ega/vault                          && \
  54 | >>>     chgrp ${LEGA_USERNAME} /ega/vault            && \
  55 | >>>     chmod 2770 /ega/vault                        && \
  56 | >>>     mkdir -p /ega/vault.bkp                      && \
  57 | >>>     chgrp ${LEGA_USERNAME} /ega/vault.bkp        && \
  58 | >>>     chmod 2770 /ega/vault.bkp                    && \
  59 | >>>     mkdir -p /etc/ega                            && \
  60 | >>>     chgrp ${LEGA_USERNAME} /etc/ega              && \
  61 | >>>     chmod 2770 /etc/ega
  62 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c ldconfig -v                                  &&     groupadd -g ${LEGA_GID} -r ${LEGA_GROUPNAME} &&     useradd -M -g ${LEGA_GROUPNAME} -u ${LEGA_UID} ${LEGA_USERNAME} &&     mkdir -p /ega/staging                        &&     chgrp ${LEGA_USERNAME} /ega/staging          &&     chmod 2770 /ega/staging                      &&     mkdir -p /ega/vault                          &&     chgrp ${LEGA_USERNAME} /ega/vault            &&     chmod 2770 /ega/vault                        &&     mkdir -p /ega/vault.bkp                      &&     chgrp ${LEGA_USERNAME} /ega/vault.bkp        &&     chmod 2770 /ega/vault.bkp                    &&     mkdir -p /etc/ega                            &&     chgrp ${LEGA_USERNAME} /etc/ega              &&     chmod 2770 /etc/ega" did not complete successfully: exit code: 4
make: *** [Makefile:62: image] Errore 1

**Comment by silverdaz** [comment]
You might want to add a little more context, rather than just pasting command-line output.

**Comment by claudiologiudice** [comment]
Hi silverdaz,
sorry, but I've just noticed that I've copied only the error.
I was able to install the toolkit but I keep having errors on the testsuite. Could you help me?

**Comment by silverdaz** [comment]
Can you elaborate on the errors?

**Comment by silverdaz** [comment]
Closing the issue as there is no progress.
If needed, create a new issue and make sure to use the "Bug Report" template.
