### ISSUE TITLE
Update the configuration module

### ISSUE THREAD

**Issue by juhtornr** [EGA-archive/LocalEGA#14]
<a href="https://github.com/silverdaz"><img src="https://avatars3.githubusercontent.com/u/465385?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silverdaz](https://github.com/silverdaz)**
_Monday Dec 10, 2018 at 18:38 GMT_
_Originally opened as https://github.com/NBISweden/LocalEGA/issues/383_

----

### Description
Segregate the configurations to only the container that needs it

### Definition of Done
Green PR

**Comment by juhtornr** [comment]
<a href="https://github.com/juhtornr"><img src="https://avatars1.githubusercontent.com/u/396559?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [juhtornr](https://github.com/juhtornr)**
_Thursday Dec 20, 2018 at 08:15 GMT_

----

@silverdaz Can you elaborate? How it works now, what is the problem and how to fix it?

**Comment by silverdaz** [comment]
Right now, one file is generated with all the settings, including sensitive information.
A better separation is to create separate specific files for each specific container.
Moreover, you avoid giving credentials to a container that has no business having those credentials.
The code for that is ready, but not merged.

**Comment by silverdaz** [comment]
Fixed by #87. Closing.
