### ISSUE TITLE
Implement support S3 storage backend for ingestion

### ISSUE THREAD

**Issue by juhtornr** [EGA-archive/LocalEGA#15]
<a href="https://github.com/silverdaz"><img src="https://avatars3.githubusercontent.com/u/465385?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silverdaz](https://github.com/silverdaz)**
_Monday Dec 10, 2018 at 18:41 GMT_
_Originally opened as https://github.com/NBISweden/LocalEGA/issues/384_

----

### Description
Make the underlying storage of the inbox an S3 instance.
The python ingestion module reads from a POSIX volume now, update it to make it read an "S3 volume" (as verify.py already does).

### Definition of Done
Green PR

**Comment by silverdaz** [comment]
The code is the inbox-s3 branch, but not merged.

**Comment by juhtornr** [comment]
Time estimate: 2 day
