### ISSUE TITLE
Update Crypt4GH to the latest version

### ISSUE THREAD

**Issue by juhtornr** [EGA-archive/LocalEGA#16]
<a href="https://github.com/silverdaz"><img src="https://avatars3.githubusercontent.com/u/465385?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silverdaz](https://github.com/silverdaz)**
_Monday Dec 10, 2018 at 18:44 GMT_
_Originally opened as https://github.com/NBISweden/LocalEGA/issues/385_

----

### Description
Update Crypt4GH to the latest version.

### Definition of Done
Green PR

**Comment by juhtornr** [comment]
<a href="https://github.com/juhtornr"><img src="https://avatars1.githubusercontent.com/u/396559?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [juhtornr](https://github.com/juhtornr)**
_Thursday Dec 20, 2018 at 08:09 GMT_

----

@silverdaz Do you mean "update ingestion to support latest Crypt4GH spec" or "update the Crypt4GH encryption tool to support the latest  Crypt4GH spec"? Also I would appreciate if you could add details about the latest version (e.g. url to latest spec).

**Comment by silverdaz** [comment]
Covered by [PR#84](https://github.com/EGA-archive/LocalEGA/pull/84)
