### ISSUE TITLE
Pipenv for managing dependencies of the project

### ISSUE THREAD

**Issue by viklund** [EGA-archive/LocalEGA#21]
### Description
To enable reproducible builds and have a better idea of what software is included in our stack we should use a tool like [pipenv](https://pipenv.readthedocs.io/en/latest/) to pin versions not only on our direct dependencies but also on our transitive dependencies.

### Definition of Done
An up to date python module lockfile is located in the root of all repositories that have python dependencies.

### How to test
The lockfile can be found in the repository and it is possible to easily install all those dependencies in a local virtual environment and then run the stack.

**Comment by silverdaz** [comment]
Implemented with a combination of requirements.txt and the setup.py (listing the dependencies).

In the docker build, the requirements are installed prior to the LocalEGA code, pinning the versions.
