### ISSUE TITLE
Refactor how we create the Docker images

### ISSUE THREAD

**Issue by jbygdell** [EGA-archive/LocalEGA#23]
### Description
Current docker images are not suited for a production environment.
To make life easier for anyone willing to test the setup we need stable versioning of all components.

### Proposed solution
- [ ]  Remove unnecessary components from the images.
- [ ] Build one image for each of the different services.
- [ ] Create tagged versions of all images, `latest` should point to the last version tagged image from `master`. This tag should be directly related to a version tag in the git repo.
- [ ] Development builds should be tagged with a corresponding `dev-latest`.
- [ ] Builds specific for each PR should be tagged `dev-PRxxx`.
- [ ] Images should automatically be built on each new tag in the master branch, via travis or docker hub.
- [ ] All images should contain labels to facilitate easy checking of the image version, see example below.
>"Labels":
>{
>"org.label-schema.build-date": "2019-01-04T01:09:04Z",
>"org.label-schema.schema-version": "1.0",
>"org.label-schema.vcs-ref": "27809385301fa082700a62ed819735f67e243852",
>"org.label-schema.vcs-url": "https://github.com/rancher/rancher.git"
>}

### Definition of Done
Each service has their own image, tagged to a specific git sha.

**Comment by silverdaz** [comment]
I was already working on it, as part of the "Improve Travis task".
I'll have a branch named `images` by the end of the day, so if you want, you can have a look and see if you can pick it up from there.

I have reduced the build time and the size of the python images already.
The openssh inbox is still based on CentOS (so...still big), and can be improved in a separate PR.
Oscar and I already have an idea how to do the latter.

The travis stages have been rearranged a bit, with a solution heavily inspired from the previous work on the nbis repo, and a bit simplified too.

**Comment by jbygdell** [comment]
Reopened due to premature closing, #25 did not address the all of the proposed solution.

**Comment by blankdots** [comment]
All PRs related to this have been merged.
