### ISSUE TITLE
Automation of test deployments using RKE

### ISSUE THREAD

**Issue by jonandernovella** [EGA-archive/LocalEGA#30]
### Description

Currently the easiest way of deploying a Kubernetes cluster for Local-EGA is by using `kubenow`, a tool that is likely to no longer be maintained. The  provided solution, based on Terraform, can provide easy automation of k8s deployments using the Rancher Kubernetes Engine.
### Definition of Done

Tests have been successfully performed with several users
### How to test

Following the instructions in: https://github.com/NBISweden/rke-openstack

**Comment by juhtornr** [comment]
There are two PR's in `rke-openstack` repo that contains the work done in this issue:
 - https://github.com/NBISweden/rke-openstack/pull/2
 - https://github.com/NBISweden/rke-openstack/pull/1

**Comment by jonandernovella** [comment]
@juhtornr Both PRs have been now merged.

**Comment by nanjiangshu** [comment]
Test succeeded on both SNIC science cloud and SafeSpring Cloud. Although on SafeSpring it is still a hack, that is, floating IPs need to be assigned to all nodes. 

It is about three times faster to deploy LocalEGA on the k8s cluster created by `rega` compared to the k8s cluster deployed by KubeNow on the same cloud resource.
Deployment time for LocalEGA is similar on SNIC Science Cloud and SafeSpring Cloud.
