### ISSUE TITLE
Database view adjustments for ega-data-api

### ISSUE THREAD

**Issue by blankdots** [EGA-archive/LocalEGA#34]
### Description
Current database view that is meant for use by EGA-data-API cannot be used as is and requires changes some changes in retrieving the data by the stable id.
e.g. in https://github.com/EGA-archive/LocalEGA/blob/master/deploy/images/db/ebi.sql#L5
the `file_id` is integer and corresponds to an internal ID used by LocalEGA to store file
while in https://github.com/EGA-archive/ega-data-api/blob/master/ega-data-api-filedatabase/src/main/resources/File.sql#L22 `file_id` was designed to be used as the `stable_id`

There are also several columns missing from https://github.com/EGA-archive/LocalEGA/blob/master/deploy/images/db/ebi.sql such as `checksum`, `checksum_type` `display_file_name`, `file_status` (even though it seems that the view is materialised with `READY` files) `file_type` does not seem to be used by `ega-data-api`

Current solution developed in `test/m4` branch of EGA-Data-API, changes the `file_id` in ega-data-api to Integer and only allows retrieval of a file with the `file_id` and not the `stable_id`.

Should files be retrievable from RES with `file_id` or `stable_id`?
RES connects directly to archive/vault.

In principle we should also consider the notes here: https://github.com/EGA-archive/ega-data-api/issues/10#issuecomment-407743725 when designing the view.

### Definition of Done
Design a view that will facilitate retrieval of archived files via their `stable_id` without adding too much overhead. Files can be retrieved with `stable_id` from DataEdge.

### How to test
Peer review and the view can be used as is by ega-data-api without huge changes to the source code.

**Comment by omllobet** [comment]
I am working on this. My current thinking is just to allow to download the files by stable_id.
