### ISSUE TITLE
Define naming conventions for Docker tags

### ISSUE THREAD

**Issue by dtitov** [EGA-archive/LocalEGA#43]
One proposed solution is to use `latest` and `stable` tags (at least). `latest` obviously stands for the latest version of an image, `stable` is supposed to mean "production stable image".

I, personally, think that `stable` is kind of redundant tag. In my mind, we should go for `latest` and release-tags (e.g. `1.0.0`), which will be the same as Git tag.

Feel free to join the discussion under this issue.

**Comment by jbygdell** [comment]
Actually you will need all of them, in this context `latest` will point to the latest development image, `stable` is the latest production ready image that will also have a semantic version tag which in turn is locked to a git sha via a git tag.

```
latest -> HEAD
PR999 -> qaz001
stable -> abc123
v1.2.3 -> abc123 <-gittag-v1.2.3
PR996 -> abc123 
v1.2.2 -> qwe987 <-gittag-v1.2.2
PR993 -> qwe987
```

`stable` and `latest` are moving targets while release tags are static.

**Comment by dtitov** [comment]
Okay, so this is just for convenience: instead of having somewhere a list with "Release tags" we will retag the latest release tags as `stable`. 

Makes sense, sounds good for me.

**Comment by blankdots** [comment]
Something to keep in mind from this article: https://blogs.msdn.microsoft.com/stevelasker/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/
* Use stable tagging for base images
* Use unique tags for deployments

I like identified tags convention here: https://forums.docker.com/t/what-is-the-naming-conventions-of-docker-tag/34042/3
```
tag           := 'latest' | version-info [ '-' distro-info ] | distro-info
version-info  := version-field [ '-' release-label ]
version-field := numeric+ [ '.' version-field ]
release-label := alpha [ alpha-numeric+ ]
distro-info   := alpha+ [ version-info ]
```

Another relevant read would if we should make use of semantic versions: https://semver.org/spec/v2.0.0.html in the format: `X.Y.Z (Major.Minor.Patch)`

This being said, my proposal would be:
* `:edge` - for changes that are so new we don't guarantee they will work;
* `:stable` - short notation of the latest stable version;
* `:stable.<timestamp>` - specific stable version for deployment purposes, e.g. how minio has it e.g. `minio/minio:RELEASE.2018-12-19T23-46-24Z` alternative we can use of semantic versions `:stable-vX.Y.Z`;
* `:latest` - we could use this in parallel with `stable`, but then not sure if we can make a clear distinction between `latest` and `stable`.

**Comment by dtitov** [comment]
This is a bit more complicated than Joakim's option. I'm for simplicity :)

**Comment by blankdots** [comment]
@dtitov i built on that version, and formalised it a bit. The only new tags I suggest are `edge` and different strategy for `stable.vX.Y.Z` instead of `vX.Y.Z` and having the `:<git_sha>`, but we can have that as optional/

**Comment by blankdots** [comment]
How about we agree on having these tags?
* `:latest` - latest code changes;
* `:stable` - latest stable version;
* `:stable.vX.Y.Z` - fix stable version.

**Comment by viklund** [comment]
I'm not sure I like using the name `stable`, I would prefer the name `release`.

**Comment by juhtornr** [comment]
How about if we do this:

- :latest - latest code changes;
- :release - latest stable version;
- :release.vX.Y.Z - fix stable version.

**Comment by viklund** [comment]
Or this:

* `:bleeding` - HEAD of `master`
* `:latest-release` - latest release
* `:vX.Y.Z` - just a release (in semver)

:scream: No `:latest`!!!

**Comment by blankdots** [comment]
I think `:edge` is a better name that `:bleeding` :syringe: .

**Comment by juhtornr** [comment]
> How about if we do this:
> 
> * :latest - latest code changes;
> * :release - latest stable version;
> * :release.vX.Y.Z - fix stable version.

This option was chosen in standup meeting.
