### ISSUE TITLE
--pythonexec option doesn't fully work

### ISSUE THREAD

**Issue by dtitov** [EGA-archive/LocalEGA#67]
### Expected Behavior
Bootstrapping works if executed as `make bootstrap ARGS='--pythonexec python3'` on the environment where `python` command stands for Python 2.7 and `python3` stands for Python 3.

### Current Behavior
```
$ make bootstrap ARGS='--pythonexec python3'
Bootstrapping Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named parse
make: *** [bootstrap] Error 1
```

### Possible Solution
`run.sh` has three entries `python -c`, which doesn't take into account the value of `PYTHONEXEC` variable.

### Steps to Reproduce
1. `make bootstrap ARGS='--pythonexec python3'`

### Context (Environment)
MacOS
`python` -> Python 2.7
`python3` -> Python 3

**Comment by wahbi** [comment]
or this : 
make bootstrap ARGS='--pythonexec python3.6'
