### ISSUE TITLE
Minio is not TLS-enabled

### ISSUE THREAD

**Issue by dtitov** [EGA-archive/LocalEGA#69]
### Expected Behavior
Minio should be serving endpoints via `https`.

### Current Behavior
Minio is serving endpoints via `http`.

### Possible Solution
In `run.sh`
```
      - ../bootstrap/certs/data/inbox-s3-backend.cert.pem:/home/.minio/public.crt
      - ../bootstrap/certs/data/inbox-s3-backend.sec.pem:/home/.minio/private.key
      - ../bootstrap/certs/data/CA.inbox-s3-backend.cert.pem:/home/.minio/CAs/LocalEGA.crt
```
should be replaced with
```
      - ../bootstrap/certs/data/inbox-s3-backend.cert.pem:/root/.minio/certs/public.crt
      - ../bootstrap/certs/data/inbox-s3-backend.sec.pem:/root/.minio/certs/private.key
      - ../bootstrap/certs/data/CA.inbox-s3-backend.cert.pem:/root/.minio/CAs/LocalEGA.crt
```

And the same for vault (archive) Minio.

### Steps to Reproduce
1. Bootstrap the current version.
2. Launch it.
3. Make sure that Minio is running on `http`.

**Comment by dtitov** [comment]
Blocked by https://github.com/EGA-archive/LocalEGA/issues/71

**Comment by silverdaz** [comment]
Minio was on purpose ignored, when we enabled TLS.

**Comment by dtitov** [comment]
Fixed.
