### ISSUE TITLE
Ingest and Verify are not TLS-enabled 

### ISSUE THREAD

**Issue by dtitov** [EGA-archive/LocalEGA#71]
### Expected Behavior
`ingest` and `verify` microservices should be able to talk to S3 over `https`.

### Current Behavior
Currently, if S3 backend (Minio in our case) is TLS-enabled, `ingest` and `verify` microservices will experience problems communicating with S3 backend:
```
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib****.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

### Possible Solution
`storage.py`:
```
...
        self.s3 = boto3.client('s3',
                               endpoint_url=self.endpoint,
                               region_name=region,
                               use_ssl=False,
                               verify=False,
                               aws_access_key_id=access_key,
                               aws_secret_access_key=secret_key)
...
```
`use_ssl` option should be set to `True` and Boto client should be aware of root CA:
> use_ssl (boolean) -- Whether or not to use SSL. By default, SSL is used. Note that not all services support non-ssl connections.
> 
> verify (boolean/string) -- Whether or not to verify SSL certificates. By default SSL certificates are verified. You can provide the following values:
> - False - do not validate SSL certificates. SSL will still be used (unless use_ssl is False), but SSL certificates will not be verified.
> - path/to/cert/bundle.pem - A filename of the CA cert bundle to uses. You can specify this argument if you want to use a different CA cert bundle than the one used by botocore.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html

Same should be fixed in tests (`test_storage.py`):
```
...
        mock_boto.assert_called_with('s3', aws_access_key_id='test', aws_secret_access_key='test',
                                     endpoint_url='http://localhost:5000', region_name='lega',
                                     use_ssl=False, verify=False)
...
```

### Steps to Reproduce
1. Enable TLS in S3 backend (https://github.com/EGA-archive/LocalEGA/pull/70)
2. Try to perform ingestion
3. `InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib****.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

### Context (Environment)
For example, Travis.

**Comment by silverdaz** [comment]
Good catch.

Minio was on purpose ignored when we enabled TLS, but the S3 connections should of course be ready to be TLS enabled, if necessary.

I'm on it.
