### ISSUE TITLE
Documentation on user management in local ega test implementation 

### ISSUE THREAD

**Issue by wahbi** [EGA-archive/LocalEGA#83]
### Description
after i Deployed LocalEGA using Docker-compose up -d , i tried to login to the inbox ,
$sudo sftp -oPort=9000 172.18.0.9
it tells me : 

Welcome to Local EGA Demo instance
Please, enter your EGA password:  ???

what is the password here and for what user ? 

is there a user management available here ?

thank you for your time.

**Comment by silverdaz** [comment]
This is normal. The users at the fake CentralEGA were not correctly setup.
(You were missing a passphrase to decrypt sensitive files from the repo.)

This is not the case anymore, if you use the latest merged PR (tag: v0.3.0), or re-pull the master branch
