### ISSUE TITLE
Provide Data Ingestion and Data API Deployment-Ready LocalEGA

### ISSUE THREAD

**Issue by juhtornr** [EGA-archive/LocalEGA#9]
<a href="https://github.com/blankdots"><img src="https://avatars3.githubusercontent.com/u/47524?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [blankdots](https://github.com/blankdots)**
_Thursday Sep 06, 2018 at 11:39 GMT_
_Originally opened as https://github.com/NBISweden/LocalEGA/issues/343_

----

Since https://github.com/NBISweden/LocalEGA/issues/204 several features have been implemented or are under development such as: https://github.com/NBISweden/LocalEGA/issues/290 or a planned: https://github.com/EGA-archive/ega-data-api/issues/10 and https://github.com/NBISweden/LocalEGA/issues/342 .
We would like to provide a deployment-ready LocalEGA where Data Ingestion and Data API work out of the box. We will focus on:
* docker-compose - available in the main LocalEGA repo (To Be Decided)
* docker swarm - https://github.com/NBISweden/LocalEGA-deploy-swarm
* kubernetes/openshift - https://github.com/NBISweden/LocalEGA-deploy-k8s
* other.

**Comment by blankdots** [comment]
No longer valid + partly completed by https://github.com/EGA-archive/LocalEGA/issues/7 and available deployments seem to be ready.
